2023/03/09 21:03:46 [error] 2087029#2087029: *13 auth request unexpected status: 405 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8085", referrer: "http://localhost:8085/auth/login"
2023/03/09 21:03:52 [error] 2087029#2087029: *7 auth request unexpected status: 405 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8085"
2023/03/09 21:03:58 [error] 2087029#2087029: *3 auth request unexpected status: 405 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8085"
2023/03/09 21:03:59 [error] 2087029#2087029: *14 auth request unexpected status: 405 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8085"
2023/03/09 21:03:59 [error] 2087029#2087029: *11 auth request unexpected status: 405 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8085"
2023/03/09 21:06:12 [error] 2087029#2087029: *419 auth request unexpected status: 405 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8085"
2023/03/09 21:11:33 [emerg] 2087939#2087939: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/09 21:11:33 [emerg] 2087939#2087939: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/09 21:11:33 [emerg] 2087939#2087939: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/09 21:11:33 [emerg] 2087939#2087939: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/09 21:11:33 [emerg] 2087939#2087939: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/09 21:11:33 [emerg] 2087939#2087939: still could not bind()
2023/03/10 12:17:10 [error] 2156614#2156614: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/"
2023/03/10 12:17:10 [error] 2156614#2156614: *1 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/"
2023/03/10 12:21:19 [error] 2156614#2156614: *185 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800"
2023/03/10 12:21:19 [error] 2156614#2156614: *185 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800"
2023/03/10 15:58:17 [error] 2156614#2156614: *351 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/stand/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished HTTP/1.1", upstream: "http://127.0.0.1:23404/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 15:58:17 [error] 2156614#2156614: *348 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", upstream: "http://127.0.0.1:23401/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 16:00:58 [error] 2156614#2156614: *383 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", upstream: "http://127.0.0.1:23401/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 16:02:26 [error] 2156614#2156614: *383 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:02:31 [error] 2156614#2156614: *570 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:02:36 [error] 2156614#2156614: *373 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:02:41 [error] 2156614#2156614: *573 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:02:46 [error] 2156614#2156614: *382 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:02:52 [error] 2156614#2156614: *376 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:02:58 [error] 2156614#2156614: *718 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:03:04 [error] 2156614#2156614: *719 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:03:10 [error] 2156614#2156614: *720 client intended to send too large body: 2804647 bytes, client: 10.5.5.16, server: localhost, request: "POST /api/v1/limonero/datasources/upload?resumableChunkNumber=1&resumableChunkSize=10485760&resumableCurrentChunkSize=2804647&resumableTotalSize=2804647&resumableType=text%2Fcsv&resumableIdentifier=2804647-sales_data_samplecsv&resumableFilename=sales_data_sample.csv&resumableRelativePath=sales_data_sample.csv&resumableTotalChunks=1&storage_id=1 HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:16:28 [error] 2170690#2170690: *172 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:16:28 [error] 2170690#2170690: *172 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:43:02 [error] 2170690#2170690: *1217 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:43:02 [error] 2170690#2170690: *1217 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:45:06 [error] 2170690#2170690: *1649 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:45:06 [error] 2170690#2170690: *1649 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:45:20 [error] 2170690#2170690: *1747 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:45:20 [error] 2170690#2170690: *1747 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:45:26 [error] 2170690#2170690: *1650 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:45:26 [error] 2170690#2170690: *1650 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/data-sources/add"
2023/03/10 16:53:33 [error] 2170690#2170690: *2499 upstream prematurely closed connection while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", upstream: "http://127.0.0.1:23401/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 16:53:33 [error] 2170690#2170690: *2671 upstream prematurely closed connection while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/stand/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished HTTP/1.1", upstream: "http://127.0.0.1:23404/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:16:54 [error] 2170690#2170690: *2701 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/stand/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished HTTP/1.1", upstream: "http://127.0.0.1:23404/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:16:55 [error] 2170690#2170690: *2707 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", upstream: "http://127.0.0.1:23401/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:17:35 [error] 2170690#2170690: *3033 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:17:35 [error] 2170690#2170690: *3033 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:18:46 [error] 2170690#2170690: *3034 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/stand/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished HTTP/1.1", upstream: "http://127.0.0.1:23404/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:18:46 [error] 2170690#2170690: *3284 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", upstream: "http://127.0.0.1:23401/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:20:26 [error] 2170690#2170690: *3332 upstream prematurely closed connection while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/caipirinha/dashboards?query=&limit=10&ascending=1&page=1&byColumn=0&asc=true&size=10&q=&fields=id,title,updated,user,is_public,hash HTTP/1.1", upstream: "http://127.0.0.1:23401/dashboards?query=&limit=10&ascending=1&page=1&byColumn=0&asc=true&size=10&q=&fields=id,title,updated,user,is_public,hash", host: "localhost:8800", referrer: "http://localhost:8800/dashboards"
2023/03/10 17:20:26 [error] 2170690#2170690: *3328 upstream prematurely closed connection while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/stand/jobs?query=&limit=10&ascending=1&page=1&byColumn=0&asc=true&size=10&name= HTTP/1.1", upstream: "http://127.0.0.1:23404/jobs?query=&limit=10&ascending=1&page=1&byColumn=0&asc=true&size=10&name=", host: "localhost:8800", referrer: "http://localhost:8800/jobs"
2023/03/10 17:20:26 [error] 2170690#2170690: *3328 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/tahiti/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&track=1&published=1&fields=id,name,user,updated,created,platform,description HTTP/1.1", upstream: "http://127.0.0.1:23403/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&track=1&published=1&fields=id,name,user,updated,created,platform,description", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:20:26 [error] 2170690#2170690: *3332 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/tahiti/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,platform,user,updated,created&types=WORKFLOW HTTP/1.1", upstream: "http://127.0.0.1:23403/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,platform,user,updated,created&types=WORKFLOW", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:20:26 [error] 2170690#2170690: *3337 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/limonero/datasources?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,description,format,updated,created HTTP/1.1", upstream: "http://127.0.0.1:23402/datasources?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,description,format,updated,created", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:20:26 [error] 2170690#2170690: *3339 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/stand/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished HTTP/1.1", upstream: "http://127.0.0.1:23404/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:20:26 [error] 2170690#2170690: *3340 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", upstream: "http://127.0.0.1:23401/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:21:43 [error] 2170690#2170690: *3346 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800"
2023/03/10 17:21:43 [error] 2170690#2170690: *3346 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", host: "localhost:8800"
2023/03/10 17:21:50 [error] 2170690#2170690: *3348 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800"
2023/03/10 17:21:50 [error] 2170690#2170690: *3348 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", host: "localhost:8800"
2023/03/10 17:21:53 [error] 2170690#2170690: *3350 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800"
2023/03/10 17:21:53 [error] 2170690#2170690: *3350 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", host: "localhost:8800"
2023/03/10 17:24:16 [error] 2170690#2170690: *3363 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", upstream: "http://127.0.0.1:23401/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created", host: "localhost:8800", referrer: "http://localhost:8800/home"
2023/03/10 17:24:29 [error] 2170690#2170690: *3368 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/stand/jobs?query=&limit=10&ascending=1&page=1&byColumn=0&asc=true&size=10&name= HTTP/1.1", upstream: "http://127.0.0.1:23404/jobs?query=&limit=10&ascending=1&page=1&byColumn=0&asc=true&size=10&name=", host: "localhost:8800", referrer: "http://localhost:8800/jobs"
2023/03/10 17:36:53 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCcDHB HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCcDHB", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:37:47 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCcQS- HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCcQS-", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:37:53 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCcRwa HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCcRwa", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:37:59 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCcTOH HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCcTOH", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:38:05 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCcUsD HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCcUsD", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:44:16 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCdvZF HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCdvZF", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:44:22 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCdwuh HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCdwuh", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:44:28 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCdyMe HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCdyMe", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:44:34 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCdzqC HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCdzqC", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:44:40 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCd_I3 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCd_I3", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:44:46 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCe0li HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCe0li", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:44:52 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCe2DV HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCe2DV", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:45:16 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCe84Q HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCe84Q", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:45:22 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCe9YQ HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCe9YQ", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:45:28 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeB00 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeB00", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:45:34 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeCTp HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeCTp", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:45:40 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeDxV HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeDxV", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:45:46 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeFPP HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeFPP", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:45:52 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeGt0 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeGt0", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:45:58 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeIKp HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeIKp", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:46:10 [error] 2178881#2178881: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeLGP HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeLGP", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:46:22 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeOBp HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeOBp", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:46:28 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCePfV HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCePfV", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:46:34 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeR7E HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeR7E", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:46:40 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeSb9 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeSb9", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:46:46 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeU2t HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeU2t", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:46:52 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeVWf HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeVWf", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:46:58 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeW-L HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeW-L", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:04 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeYRz HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeYRz", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:10 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCeZvo HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCeZvo", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:16 [error] 2178881#2178881: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORCebNS HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORCebNS", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:32 [error] 2178881#2178881: *129 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:32 [error] 2178881#2178881: *129 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:50 [error] 2178881#2178881: *127 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:50 [error] 2178881#2178881: *127 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:55 [error] 2178881#2178881: *126 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:47:55 [error] 2178881#2178881: *126 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:48:01 [error] 2178881#2178881: *365 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:48:01 [error] 2178881#2178881: *365 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:49:19 [error] 2178881#2178881: *669 connect() failed (111: Connection refused) while connecting to upstream, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/10 17:49:19 [error] 2178881#2178881: *669 auth request unexpected status: 502 while sending to client, client: 10.5.5.16, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:8800", referrer: "http://localhost:8800/admin/ws-ping"
2023/03/13 11:48:24 [emerg] 2436064#2436064: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/13 11:48:24 [emerg] 2436064#2436064: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/13 11:48:24 [emerg] 2436064#2436064: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/13 11:48:24 [emerg] 2436064#2436064: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/13 11:51:38 [error] 2178881#2178881: *1269 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORQpz13 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORQpz13", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/13 11:51:41 [error] 2178881#2178881: *1269 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORQpzm3 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORQpzm3", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/13 11:51:44 [error] 2178881#2178881: *1269 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORQp-Uz HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORQp-Uz", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/13 11:59:04 [error] 2178881#2178881: *1284 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORQrfxF HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORQrfxF", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/13 11:59:06 [error] 2178881#2178881: *1284 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORQrgQW HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORQrgQW", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/13 11:59:10 [error] 2178881#2178881: *1284 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORQrhOz HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORQrhOz", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/13 11:59:15 [error] 2178881#2178881: *1284 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORQrid6 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORQrid6", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/13 14:11:08 [error] 2178881#2178881: *1530 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /experiments/visualization/design/1 HTTP/1.1", upstream: "http://127.0.0.1:8081/experiments/visualization/design/1", host: "localhost:23456"
2023/03/14 01:35:43 [error] 2446593#2446593: *675 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTmapQ HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTmapQ", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/14 01:35:45 [error] 2446593#2446593: *675 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTmbIb HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTmbIb", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/14 01:35:48 [error] 2446593#2446593: *675 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTmc1O HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTmc1O", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/14 01:44:19 [error] 2446593#2446593: *764 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORToYnq HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORToYnq", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/1"
2023/03/14 01:46:31 [error] 2484979#2484979: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTp30T HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTp30T", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:46:37 [error] 2484979#2484979: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTp4UA HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTp4UA", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:46:56 [error] 2484979#2484979: *13 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:46:56 [error] 2484979#2484979: *13 auth request unexpected status: 502 while sending to client, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:49:34 [error] 2484979#2484979: *604 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTplhi HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTplhi", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:49:40 [error] 2484979#2484979: *604 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTpn9S HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTpn9S", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:49:46 [error] 2484979#2484979: *604 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTpod9 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTpod9", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:49:52 [error] 2484979#2484979: *604 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTpq4y HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTpq4y", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:49:58 [error] 2484979#2484979: *604 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTprYm HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTprYm", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:50:03 [error] 2484979#2484979: *604 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTpsnh HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTpsnh", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:51:21 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTq9pX HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTq9pX", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:51:27 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqBHM HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqBHM", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:51:33 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqCl4 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqCl4", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:51:39 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqECt HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqECt", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:51:45 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqFga HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqFga", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:51:51 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqH8G HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqH8G", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:51:57 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqIc4 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqIc4", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:02 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqJrD HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqJrD", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:08 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqLHu HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqLHu", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:14 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqMlg HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqMlg", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:20 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqODS HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqODS", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:26 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqPh9 HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqPh9", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:32 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqR8v HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqR8v", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:38 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqSco HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqSco", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:44 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqU4W HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqU4W", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/14 01:52:50 [error] 2484979#2484979: *606 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /socket.io/?EIO=3&transport=polling&t=ORTqVYK HTTP/1.1", upstream: "http://127.0.0.1:23404/socket.io/?EIO=3&transport=polling&t=ORTqVYK", host: "localhost:23456", referrer: "http://localhost:23456/admin/ws-ping"
2023/03/15 18:41:15 [error] 2522826#2522826: *700 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "localhost:23456"
2023/03/15 18:41:15 [error] 2522826#2522826: *700 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8081/favicon.ico", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/15 18:41:17 [error] 2522826#2522826: *700 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "localhost:23456"
2023/03/15 18:41:17 [error] 2522826#2522826: *700 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8081/favicon.ico", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/15 18:42:22 [error] 2522826#2522826: *706 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "localhost:23456"
2023/03/15 18:42:22 [error] 2522826#2522826: *706 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8081/favicon.ico", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/15 18:42:26 [error] 2522826#2522826: *706 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "localhost:23456"
2023/03/15 18:42:26 [error] 2522826#2522826: *706 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8081/favicon.ico", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 12:48:38 [error] 2522826#2522826: *712 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "localhost:8800"
2023/03/16 12:48:38 [error] 2522826#2522826: *712 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8081/favicon.ico", host: "localhost:8800", referrer: "http://localhost:8800/"
2023/03/16 12:48:40 [error] 2522826#2522826: *712 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "localhost:8800"
2023/03/16 12:48:40 [error] 2522826#2522826: *712 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8081/favicon.ico", host: "localhost:8800", referrer: "http://localhost:8800/"
2023/03/16 13:31:23 [emerg] 2693840#2693840: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:31:23 [emerg] 2693840#2693840: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:31:23 [emerg] 2693840#2693840: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:31:23 [emerg] 2693840#2693840: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:31:23 [emerg] 2693840#2693840: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:31:23 [emerg] 2693840#2693840: still could not bind()
2023/03/16 13:38:30 [emerg] 2694397#2694397: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:38:30 [emerg] 2694397#2694397: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:38:30 [emerg] 2694397#2694397: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:38:30 [emerg] 2694397#2694397: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:38:30 [emerg] 2694397#2694397: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:38:30 [emerg] 2694397#2694397: still could not bind()
2023/03/16 13:39:07 [emerg] 2694453#2694453: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:39:07 [emerg] 2694453#2694453: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:39:07 [emerg] 2694453#2694453: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:39:07 [emerg] 2694453#2694453: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:39:07 [emerg] 2694453#2694453: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:39:07 [emerg] 2694453#2694453: still could not bind()
2023/03/16 13:44:00 [emerg] 2694774#2694774: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:44:00 [emerg] 2694774#2694774: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:44:00 [emerg] 2694774#2694774: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:44:00 [emerg] 2694774#2694774: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:44:00 [emerg] 2694774#2694774: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:44:00 [emerg] 2694774#2694774: still could not bind()
2023/03/16 13:52:06 [emerg] 2695299#2695299: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:52:06 [emerg] 2695299#2695299: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:52:06 [emerg] 2695299#2695299: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:52:06 [emerg] 2695299#2695299: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:52:06 [emerg] 2695299#2695299: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:52:06 [emerg] 2695299#2695299: still could not bind()
2023/03/16 13:58:37 [emerg] 2695755#2695755: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:58:37 [emerg] 2695755#2695755: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:58:37 [emerg] 2695755#2695755: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:58:37 [emerg] 2695755#2695755: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:58:37 [emerg] 2695755#2695755: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 13:58:37 [emerg] 2695755#2695755: still could not bind()
2023/03/16 14:04:44 [emerg] 2696131#2696131: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:04:44 [emerg] 2696131#2696131: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:04:44 [emerg] 2696131#2696131: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:04:44 [emerg] 2696131#2696131: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:04:44 [emerg] 2696131#2696131: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:04:44 [emerg] 2696131#2696131: still could not bind()
2023/03/16 14:07:39 [crit] 2522826#2522826: *721 open() "/tmp/proxy_tmp/9/02/0000000029" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:07:39 [crit] 2522826#2522826: *729 open() "/tmp/proxy_tmp/0/03/0000000030" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:07:39 [crit] 2522826#2522826: *718 open() "/tmp/proxy_tmp/1/03/0000000031" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:07:39 [crit] 2522826#2522826: *728 open() "/tmp/proxy_tmp/2/03/0000000032" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:07:39 [crit] 2522826#2522826: *727 open() "/tmp/proxy_tmp/3/03/0000000033" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:07:40 [crit] 2522826#2522826: *722 open() "/tmp/proxy_tmp/4/03/0000000034" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:07:40 [crit] 2522826#2522826: *822 open() "/tmp/proxy_tmp/5/03/0000000035" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:07:51 [crit] 2522826#2522826: *828 open() "/tmp/proxy_tmp/6/03/0000000036" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:07:51 [crit] 2522826#2522826: *988 open() "/tmp/proxy_tmp/7/03/0000000037" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:08:34 [crit] 2522826#2522826: *824 open() "/tmp/proxy_tmp/8/03/0000000038" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:08:34 [crit] 2522826#2522826: *1126 open() "/tmp/proxy_tmp/9/03/0000000039" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:09:40 [crit] 2522826#2522826: *1149 open() "/tmp/proxy_tmp/0/04/0000000040" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:09:40 [crit] 2522826#2522826: *1328 open() "/tmp/proxy_tmp/1/04/0000000041" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:09:47 [crit] 2522826#2522826: *1158 open() "/tmp/proxy_tmp/2/04/0000000042" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:47 [crit] 2522826#2522826: *1159 open() "/tmp/proxy_tmp/3/04/0000000043" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:47 [crit] 2522826#2522826: *1157 open() "/tmp/proxy_tmp/4/04/0000000044" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:47 [crit] 2522826#2522826: *1148 open() "/tmp/proxy_tmp/5/04/0000000045" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:47 [crit] 2522826#2522826: *1153 open() "/tmp/proxy_tmp/6/04/0000000046" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:47 [crit] 2522826#2522826: *1338 open() "/tmp/proxy_tmp/7/04/0000000047" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:49 [crit] 2522826#2522826: *1340 open() "/tmp/proxy_tmp/8/04/0000000048" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:49 [crit] 2522826#2522826: *1341 open() "/tmp/proxy_tmp/9/04/0000000049" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:49 [crit] 2522826#2522826: *1344 open() "/tmp/proxy_tmp/0/05/0000000050" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:53 [crit] 2522826#2522826: *1346 open() "/tmp/proxy_tmp/1/05/0000000051" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:54 [crit] 2522826#2522826: *1347 open() "/tmp/proxy_tmp/2/05/0000000052" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:54 [crit] 2522826#2522826: *1349 open() "/tmp/proxy_tmp/3/05/0000000053" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:54 [crit] 2522826#2522826: *1352 open() "/tmp/proxy_tmp/4/05/0000000054" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:58 [crit] 2522826#2522826: *1354 open() "/tmp/proxy_tmp/5/05/0000000055" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:59 [crit] 2522826#2522826: *1355 open() "/tmp/proxy_tmp/6/05/0000000056" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:59 [crit] 2522826#2522826: *1357 open() "/tmp/proxy_tmp/7/05/0000000057" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:59 [crit] 2522826#2522826: *1361 open() "/tmp/proxy_tmp/8/05/0000000058" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:59 [crit] 2522826#2522826: *1360 open() "/tmp/proxy_tmp/9/05/0000000059" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:09:59 [crit] 2522826#2522826: *1364 open() "/tmp/proxy_tmp/0/06/0000000060" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:10:05 [crit] 2522826#2522826: *1366 open() "/tmp/proxy_tmp/1/06/0000000061" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:10:05 [crit] 2522826#2522826: *1367 open() "/tmp/proxy_tmp/2/06/0000000062" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:10:05 [crit] 2522826#2522826: *1370 open() "/tmp/proxy_tmp/3/06/0000000063" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:10:43 [crit] 2696905#2696905: *9 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:10:43 [error] 2696905#2696905: *9 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:10:44 [crit] 2696905#2696905: *1 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:10:44 [error] 2696905#2696905: *1 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:10:55 [crit] 2696905#2696905: *103 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:10:55 [error] 2696905#2696905: *103 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:10:55 [crit] 2696905#2696905: *5 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:10:55 [error] 2696905#2696905: *5 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:11:10 [crit] 2696905#2696905: *12 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:11:10 [error] 2696905#2696905: *12 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:11:23 [crit] 2696905#2696905: *10 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:11:23 [error] 2696905#2696905: *10 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:11:33 [crit] 2696907#2696907: opendir() "/tmp/custom_nginx" failed (13: Permission denied)
2023/03/16 14:12:05 [crit] 2696905#2696905: *2 open() "/tmp/proxy_tmp/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:05 [crit] 2696905#2696905: *147 open() "/tmp/proxy_tmp/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:05 [crit] 2696905#2696905: *150 open() "/tmp/proxy_tmp/3/00/0000000003" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:06 [crit] 2696905#2696905: *152 open() "/tmp/proxy_tmp/4/00/0000000004" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:08 [crit] 2696905#2696905: *153 open() "/tmp/proxy_tmp/5/00/0000000005" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:08 [crit] 2696905#2696905: *155 open() "/tmp/proxy_tmp/6/00/0000000006" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:08 [crit] 2696905#2696905: *158 open() "/tmp/proxy_tmp/7/00/0000000007" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:13 [crit] 2696905#2696905: *160 open() "/tmp/proxy_tmp/8/00/0000000008" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:14 [crit] 2696905#2696905: *161 open() "/tmp/proxy_tmp/9/00/0000000009" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:14 [crit] 2696905#2696905: *163 open() "/tmp/proxy_tmp/0/01/0000000010" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:12:14 [crit] 2696905#2696905: *166 open() "/tmp/proxy_tmp/1/01/0000000011" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:15:23 [crit] 2697484#2697484: *1 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:15:23 [error] 2697484#2697484: *1 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:15:52 [crit] 2697484#2697484: *2 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:15:52 [error] 2697484#2697484: *2 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:15:53 [crit] 2697484#2697484: *4 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:15:53 [error] 2697484#2697484: *4 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:15:53 [crit] 2697484#2697484: *8 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:15:53 [error] 2697484#2697484: *8 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:15:53 [crit] 2697484#2697484: *6 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:15:53 [error] 2697484#2697484: *6 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:16:16 [crit] 2697484#2697484: *9 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:16:16 [error] 2697484#2697484: *9 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:16:18 [crit] 2697486#2697486: opendir() "/tmp/custom_nginx" failed (13: Permission denied)
2023/03/16 14:18:37 [crit] 2697860#2697860: *1 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:18:37 [error] 2697860#2697860: *1 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:19:13 [crit] 2697919#2697919: *1 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/users HTTP/1.1", subrequest: "/auth/internal", host: "localhost:8800"
2023/03/16 14:19:13 [error] 2697919#2697919: *1 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/users HTTP/1.1", host: "localhost:8800"
2023/03/16 14:20:30 [crit] 2698030#2698030: *1 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:20:30 [error] 2698030#2698030: *1 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:20:56 [crit] 2698030#2698030: *2 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456"
2023/03/16 14:20:56 [error] 2698030#2698030: *2 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", host: "localhost:23456"
2023/03/16 14:24:54 [crit] 2698434#2698434: *1 open() "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied), client: 127.0.0.1, server: localhost, request: "POST /api/v1/thorn/auth/login HTTP/1.1", subrequest: "/auth/internal", host: "localhost:23456", referrer: "http://localhost:23456/auth/login"
2023/03/16 14:24:54 [error] 2698434#2698434: *1 auth request unexpected status: 500, client: 127.0.0.1, server: localhost, request: "POST /api/v1/thorn/auth/login HTTP/1.1", host: "localhost:23456", referrer: "http://localhost:23456/auth/login"
2023/03/16 14:25:45 [crit] 2698436#2698436: opendir() "/tmp/custom_nginx" failed (13: Permission denied)
2023/03/16 14:26:59 [crit] 2698434#2698434: *2 rename() "/tmp/proxy_tmp/1/00/0000000001" to "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:27:05 [crit] 2698434#2698434: *2 rename() "/tmp/proxy_tmp/2/00/0000000002" to "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:27:11 [crit] 2698434#2698434: *2 rename() "/tmp/proxy_tmp/3/00/0000000003" to "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "POST /api/v1/thorn/auth/login HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/auth/login"
2023/03/16 14:27:11 [crit] 2698434#2698434: *2 rename() "/tmp/proxy_tmp/4/00/0000000004" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&track=1&published=1&fields=id,name,user,updated,created,platform,description HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:27:12 [crit] 2698434#2698434: *13 rename() "/tmp/proxy_tmp/5/00/0000000005" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/limonero/datasources?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,description,format,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:27:12 [crit] 2698434#2698434: *3 rename() "/tmp/proxy_tmp/6/00/0000000006" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,platform,user,updated,created&types=WORKFLOW HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:27:12 [crit] 2698434#2698434: *14 rename() "/tmp/proxy_tmp/7/00/0000000007" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/stand/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:27:13 [crit] 2698434#2698434: *15 rename() "/tmp/proxy_tmp/8/00/0000000008" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:28:18 [crit] 2698434#2698434: *25 rename() "/tmp/proxy_tmp/9/00/0000000009" to "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456"
2023/03/16 14:28:26 [crit] 2698434#2698434: *25 rename() "/tmp/proxy_tmp/0/01/0000000010" to "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:28:27 [crit] 2698434#2698434: *38 rename() "/tmp/proxy_tmp/1/01/0000000011" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&track=1&published=1&fields=id,name,user,updated,created,platform,description HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:28:28 [crit] 2698434#2698434: *33 rename() "/tmp/proxy_tmp/2/01/0000000012" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,platform,user,updated,created&types=WORKFLOW HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:28:28 [crit] 2698434#2698434: *37 rename() "/tmp/proxy_tmp/3/01/0000000013" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/limonero/datasources?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,description,format,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:28:29 [crit] 2698434#2698434: *25 rename() "/tmp/proxy_tmp/4/01/0000000014" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:28:29 [crit] 2698434#2698434: *26 rename() "/tmp/proxy_tmp/5/01/0000000015" to "/tmp/custom_nginx/b87178cf08cfccb641e968c7da040535" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/stand/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:31:24 [emerg] 2699197#2699197: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:31:24 [emerg] 2699197#2699197: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:31:24 [emerg] 2699197#2699197: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:31:24 [emerg] 2699197#2699197: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:31:24 [emerg] 2699197#2699197: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:31:24 [emerg] 2699197#2699197: still could not bind()
2023/03/16 14:32:42 [emerg] 2699381#2699381: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:32:42 [emerg] 2699381#2699381: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:32:42 [emerg] 2699381#2699381: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:32:42 [emerg] 2699381#2699381: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:32:42 [emerg] 2699381#2699381: bind() to 0.0.0.0:8800 failed (98: Address already in use)
2023/03/16 14:32:42 [emerg] 2699381#2699381: still could not bind()
2023/03/16 14:42:03 [crit] 2698434#2698434: *208 rename() "/tmp/proxy_tmp/6/01/0000000016" to "/tmp/custom_nginx/d41d8cd98f00b204e9800998ecf8427e" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/thorn/public/configurations/OPENID_CONFIG HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/"
2023/03/16 14:42:04 [crit] 2698434#2698434: *201 rename() "/tmp/proxy_tmp/7/01/0000000017" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/limonero/datasources?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,description,format,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:42:05 [crit] 2698434#2698434: *202 rename() "/tmp/proxy_tmp/8/01/0000000018" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&fields=id,name,platform,user,updated,created&types=WORKFLOW HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:42:05 [crit] 2698434#2698434: *206 rename() "/tmp/proxy_tmp/9/01/0000000019" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/workflows?enabled=1&page=1&sort=updated&asc=false&size=5&track=1&published=1&fields=id,name,user,updated,created,platform,description HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:42:06 [crit] 2698434#2698434: *208 rename() "/tmp/proxy_tmp/0/02/0000000020" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/stand/jobs?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,user,workflow,status,created,finished HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:42:06 [crit] 2698434#2698434: *198 rename() "/tmp/proxy_tmp/1/02/0000000021" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/caipirinha/dashboards?enabled=1&page=1&sort=created&asc=false&size=5&fields=id,title,user,updated,created HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/home"
2023/03/16 14:42:10 [crit] 2698434#2698434: *198 rename() "/tmp/proxy_tmp/2/02/0000000022" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/workflows?query=&limit=5&ascending=1&page=1&byColumn=0&asc=true&size=5&platform=meta&types=experiment&fields=id,name,platform,updated,user,version,description,type&enabled=1 HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/experiments"
2023/03/16 14:42:19 [crit] 2698434#2698434: *208 rename() "/tmp/proxy_tmp/3/02/0000000023" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/limonero/datasources?sort=name&size=20&name=t&enabled=true&simple=true&fields=id,name HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/new"
2023/03/16 14:42:21 [crit] 2698434#2698434: *208 rename() "/tmp/proxy_tmp/4/02/0000000024" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/limonero/datasources/1 HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/new"
2023/03/16 14:42:23 [crit] 2698434#2698434: *208 rename() "/tmp/proxy_tmp/5/02/0000000025" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "POST /api/v1/tahiti/workflows HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/new"
2023/03/16 14:42:24 [crit] 2698434#2698434: *206 rename() "/tmp/proxy_tmp/6/02/0000000026" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/operations?category=visualization-builder&platform=1000&fields=id,forms,categories,name,slug HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/2"
2023/03/16 14:42:24 [crit] 2698434#2698434: *206 rename() "/tmp/proxy_tmp/7/02/0000000027" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/tahiti/workflows/2 HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/2"
2023/03/16 14:42:25 [crit] 2698434#2698434: *206 rename() "/tmp/proxy_tmp/8/02/0000000028" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/limonero/datasources/1 HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/2"
2023/03/16 14:42:25 [crit] 2698434#2698434: *206 rename() "/tmp/proxy_tmp/9/02/0000000029" to "/tmp/custom_nginx/e7fded76db2746825c2daea29b2f8403" failed (13: Permission denied) while reading upstream, client: 127.0.0.1, server: localhost, request: "GET /api/v1/stand/clusters?enabled=true&platform=4 HTTP/1.1", subrequest: "/auth/internal", upstream: "http://127.0.0.1:23400/auth/validate", host: "localhost:23456", referrer: "http://localhost:23456/experiments/visualization/design/2"
